name: Test

on:
  push:
    branches: ["main", "test"]
  pull_request:
    branches: ["main", "test"]
  schedule:
    # Run every Monday at 00:00 UTC
    - cron: '0 0 * * 1'

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Check version
        run: deno -V

      - name: Verify formatting
        run: deno fmt --check

      - name: Run tests
        run: deno test --unstable-kv --coverage=./coverage ./tests/thoth-test.ts

      - name: View coverage
        run: |
            # reference: https://github.com/jhechtf/code-coverage
            deno install --allow-read --no-check -n code-coverage https://deno.land/x/code_coverage/cli.ts &&
            deno coverage --exclude=tests/work/ --lcov --output=lcov.info ./coverage/ &&
            code-coverage --file lcov.info